Enabling dynamic canister creation on playground
dfinity/motoko-playground pull request #118
Opened 2022-07-25 17:48 UTC by kentosugama

Previously, cycle transfers were disabled on the playground to prevent users from transferring cycles from the Playground canisters to their own canisters. This prevented users from dynamically spawning canisters in their Playground code.

The fix proposed by @chenyan-dfinity is to allow dynamic canister creation, but instead of actually spawning new canisters to return some unused canister already managed by the Playground pool.

This PR (in conjunction with this PR to `ic-wasm` https://github.com/dfinity/ic-wasm/pull/16) redirects system calls to the management canister to the playground backend, including create_canister, to implement the fix.

2022-07-25 18:05 UTC, chenyan-dfinity commented on service/pool/Main.mo
> +        await IC.delete_canister({ canister_id });
Cannot call `delete_canister`. Redirect to `removeCode`.

2022-07-25 18:05 UTC, chenyan-dfinity commented on service/pool/Main.mo
> +        await IC.uninstall_code({ canister_id });
Redirect to `removeCode`

2022-07-25 18:05 UTC, chenyan-dfinity commented on service/pool/Main.mo
> +        await IC.install_code({ arg; wasm_module; mode; canister_id });
Better to redirect to `installCode`, and not doing the recursive transformation in ic-wasm.

2022-07-25 18:05 UTC, chenyan-dfinity commented on service/wasm-utils/Cargo.toml
> +ic-types = "0.3.0"
```suggestion
ic-types = "0.4.0"
```

2022-07-25 18:06 UTC, kentosugama commented on service/pool/Main.mo
> +import Debug "mo:base/Debug";
Nope, I was just debugging with it. Will remove

2022-07-28 21:25 UTC, chenyan-dfinity commented on service/pool/Main.mo
>          pool.unshare(stablePool);
We need a step to migrate data from `pool` to `metadata`.

2022-07-28 21:25 UTC, chenyan-dfinity commented on service/pool/Main.mo
> +                    nonceCache.add(nonce!);
May be cleaner to move the `nonce` logic out of this function. It's okay to cache the nounce even if the related async call fails.

2022-07-28 21:25 UTC, chenyan-dfinity commented on service/pool/Types.mo
> +        var map = TrieMap.TrieMap<Principal, (Int, Bool)>(Principal.equal, Principal.hash);
Is it cleaner to add this map inside the `CanisterPool` class, and update both map in each class method? This way, we don't need to do anything on the caller side (the main actor code).

2022-07-28 21:25 UTC, chenyan-dfinity commented on service/pool/Main.mo
> +                ignore await installCode(info, args, profiling);
Remember to disable the recursion in ic-wasm

2022-07-29 15:59 UTC, kentosugama commented on service/pool/Types.mo
> +        var map = TrieMap.TrieMap<Principal, (Int, Bool)>(Principal.equal, Principal.hash);
Sure, sounds good

2022-07-29 15:59 UTC, kentosugama commented on service/pool/Main.mo
> +                ignore await installCode(info, args, profiling);
Yup

2022-07-31 21:22 UTC, chenyan-dfinity commented on service/pool/Types.mo
> +            Iter.iterate<CanisterInfo>(list.vals(), func(info, _) = metadata.put(info.id, (info.timestamp, false)));
Then we are losing the `profiling` field after the upgrade. We can extend `CanisterInfo` with a new optional field `profiling : ?Bool` to store this info in the splay tree.

2022-08-01 16:45 UTC, kentosugama commented on service/pool/Types.mo
> +        var childrens = TrieMap.TrieMap<Principal, TrieSet.Set<Principal>>(Principal.equal, Principal.hash);
Sounds good on the # of children limitation.

I considered some kind of similar structure (didn't know Mathew's existed), but I thought the generality wasn't necessary since a child has 1 parent only. So, we only we need to work with a map from X --> {Y} and a map from Y --> X. 

Thought this might run faster. But since's Mathew's implementation already exists, if it's cleaner to use it, I'll swap it out!

(Btw didn't know that Trie2Ds were a thing! Would have used that instead of TrieSet, but I guess I'll use an array anyway).

2022-08-01 16:45 UTC, kentosugama commented on service/pool/Types.mo
> +            Iter.iterate<CanisterInfo>(list.vals(), func(info, _) = metadata.put(info.id, (info.timestamp, false)));
Sounds good, will add

2022-08-09 02:02 UTC, chenyan-dfinity commented on service/pool/Types.mo
> +                    Principal.equal(registerdParent, parent)
Need to check if `registeredParent` has reached TTL. If so, we return false and delete this entry.

2022-08-09 16:58 UTC, kentosugama commented on service/pool/Main.mo
> +                await IC.start_canister cid;
Right, I thought about doing this, but the pattern match looked ugly so I omitted it for readability

2022-08-09 17:03 UTC, kentosugama commented on service/pool/Main.mo
> +        if (not pool.find info) {
Yeah I was just getting too excited removing parenthesis. I'll add these back

2022-08-09 17:24 UTC, kentosugama commented on service/pool/Main.mo
> +        if (not pool.find info) {
So I should put parenthesis for all function application?

2022-08-09 17:28 UTC, kentosugama commented on service/pool/Types.mo
> +                    Principal.equal(registerdParent, parent)
So I don't think we're strictly enforcing TTL expiration in the playground, until that canister is requested by another user. I was following the same approach here, where the parent would be allowed to keep executing until someone actually claimed that canister (at which point `isParentOf` will return false).

2022-08-09 17:58 UTC, chenyan-dfinity commented on service/pool/Types.mo
> +                    Principal.equal(registerdParent, parent)
Yes, that would work, and probably cleaner: when someone claimed the canister, we delete the subtree. So we need to add the code to `getExpiredCanisterInfo`.

2022-08-09 17:58 UTC, chenyan-dfinity commented on service/pool/Main.mo
> +        if (not pool.find info) {
I'm neutral on the style. Just thinking removing parenthesis for all existing functions is a bit extreme :)

2022-08-09 18:01 UTC, chenyan-dfinity commented on service/pool/Main.mo
> +                await IC.start_canister cid;
Yeah, inter-canister calls are expensive. That takes precedence over readability.

2022-08-09 18:21 UTC, kentosugama commented on service/pool/Types.mo
> +                    Principal.equal(registerdParent, parent)
I have that [here](https://github.com/dfinity/motoko-playground/blob/d5b1f5e15f379bb806b1bcd1273a36dd9df0c9d1/service/pool/Types.mo#L67).

I'm only deleting that single node from the tree (instead of recursively deleting the subtree), since maybe the child hasn't expired yet, and might have its own children.

2022-08-09 18:26 UTC, chenyan-dfinity commented on service/pool/Types.mo
> +                    Principal.equal(registerdParent, parent)
Ah, looks good!

2022-08-09 20:32 UTC, chenyan-dfinity commented on service/pool/Main.mo
> +    private func sanitizeInputs(caller: Principal, callee: Principal, methodName: Text) : async Types.CanisterInfo {
How about we return `Result<CanisterInfo, Text>`, and throw on the caller side? This can eliminate another async call.

2022-08-09 20:32 UTC, chenyan-dfinity commented on service/pool/Types.mo
> +                            let new_info = { timestamp = now; id = info.id; profiling = info.profiling };
```suggestion
                            let new_info = { timestamp = now; id = info.id; profiling = ?false };
```

2022-08-09 20:32 UTC, chenyan-dfinity commented on service/pool/Types.mo
> +                            metadata.put(new_info.id, (new_info.timestamp, unwrapProfiling(new_info)));
```suggestion
                            metadata.put(new_info.id, (new_info.timestamp, false));
```

2022-08-09 20:32 UTC, chenyan-dfinity commented on src/build.ts
> +    profiling: info.profiling,
Is this field needed? It's always false.

2022-08-09 22:02 UTC, kentosugama commented on service/pool/Types.mo
> +                            metadata.put(new_info.id, (new_info.timestamp, unwrapProfiling(new_info)));
Ahh right good catch

2022-08-09 22:03 UTC, kentosugama commented on src/build.ts
> +    profiling: info.profiling,
I get a missing error field if I remove it (from both here and the type declaration).

2022-08-11 01:48 UTC, chenyan-dfinity commented on src/build.ts
> +    profiling: info.profiling,
The root problem is in `install`, I made a commit to fix it. Please double check I didn't mess up with anything.

2022-08-11 18:06 UTC, kentosugama commented on src/build.ts
> +    profiling: info.profiling,
Thank you

2022-08-11 23:37 UTC, chenyan-dfinity approved these changes

2022-08-12 03:29 UTC, chenyan-dfinity requested changes
Sorry, my bad. I forget the stable subtyping rule is different from Candid, so we cannot add optional field...I will add a CI test tomorrow to catch this early. Then the `profiling` field can only appear in `metadata`, not in `CanisterInfo`.

2022-08-14 20:50 UTC, chenyan-dfinity commented
Works now. `InitParams` still cannot be preserved after upgrade, but that's okay. I add a "breaking changes" label to prevent CI from complaining.

2022-08-15 22:59 UTC, chenyan-dfinity approved these changes
LGTM!

2022-08-15 23:09 UTC, merged